In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
df=pd.read_excel("/content/نسخة_من_إختبار_بندرالجديد_الردود.xlsx")

In [3]:
df.head()

,رقم الحالة,الاسم,النوع,الصف الدراسي,العمر,التسلسل,موضع الرسم,المسافة بين رسمين,الاتصال أو التصادم,استخدام الهامش,تغيير موضع الورقة,التغيرات في الجشطالت,ملاحظات دالة بشكل عام,التصنيفات المرضية,التعليق العام
0,1,ياسين محمود علي حسن,ذكر,الرابع الإبتدائي,9,تسلسل غير منظم,لا,من 0.75 إلى 1.25 سم,لا يوجد تداخل,لا,لا,"صعوبات الإغلاق, التغير في الانحناءات",لا يوجد,سوي,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...
1,2,عمرو احمد محمد فتحي,ذكر,الرابع الإبتدائي,9,تسلسل منظم,لا,من 0.75 إلى 1.25 سم,لا يوجد تداخل,لا,لا,"صعوبات الإغلاق - التغير في الانحناءات, التغير ...",إعادة رسم الأجزاء (خطوط ثقيلة),سوي,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...
2,3,محمد سيد البدري عبد المطلب,ذكر,الرابع الإبتدائي,9,تسلسل غير منظم,لا,من 0.75 إلى 1.25 سم,لا يوجد تداخل,لا,لا,"صعوبات الإغلاق, صعوبات التقاطع, التغير في الان...","اندفاع وسرعة في الرسم, المداومة",سوي,المفحوص بشكل عام سوي ويتمتع بمستوى متوسط من ال...
3,4,عدي هاني سيد محمد,ذكر,الرابع الإبتدائي,10,تسلسل غير منظم,لا,مسافة صغيرة جداً,لا يوجد تداخل,لا,لا,"صعوبات الإغلاق, صعوبات التقاطع, التغير في الان...",المداومة,سوي,المفحوص بشكل عام سوي ويتمتع بقدرة متوسطة على ا...
4,5,عمر حاتم عمر الفاروق,ذكر,الرابع الإبتدائي,11,تسلسل غير منظم,لا,مسافة صغيرة جداً,تصادم أو نزعة إليه,لا,لا,"التغير في الانحناءات, صعوبة رسم الأشكال المتداخلة",لا يوجد,سوي,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   رقم الحالة             89 non-null     int64
 1   الاسم                  89 non-null     object
 2   النوع                  89 non-null     object
 3   الصف الدراسي           89 non-null     object
 4   العمر                  89 non-null     int64
 5   التسلسل                89 non-null     object
 6   موضع الرسم             89 non-null     object
 7   المسافة بين رسمين      89 non-null     object
 8   الاتصال أو التصادم     89 non-null     object
 9   استخدام الهامش         89 non-null     object
 10  تغيير موضع الورقة      89 non-null     object
 11  التغيرات في الجشطالت   89 non-null     object
 12  ملاحظات دالة بشكل عام  89 non-null     object
 13  التصنيفات المرضية      89 non-null     object
 14  التعليق العام          89 non-null     object
dtypes: int64(2), object(13)
memory usage: 10.6+ KB

In [5]:
df = df.drop(columns=['رقم الحالة', 'الاسم'])

In [6]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

In [7]:
df.isnull().sum()

النوع                    0
الصف الدراسي             0
العمر                    0
التسلسل                  0
موضع الرسم               0
المسافة بين رسمين        0
الاتصال أو التصادم       0
استخدام الهامش           0
تغيير موضع الورقة        0
التغيرات في الجشطالت     0
ملاحظات دالة بشكل عام    0
التصنيفات المرضية        0
التعليق العام            0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

le = LabelEncoder()
df['النوع'] = le.fit_transform(df['النوع'])

In [9]:
df["استخدام الهامش"] = le.fit_transform(df["استخدام الهامش"])
df["موضع الرسم"] = le.fit_transform(df["موضع الرسم"])
df["تغيير موضع الورقة"] = le.fit_transform(df["تغيير موضع الورقة"])
df["المسافة بين رسمين"] = le.fit_transform(df["المسافة بين رسمين"])

In [10]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder_1 = OrdinalEncoder(categories=[["لا يوجد تداخل", "تداخل الرسوم", "تصادم أو نزعة إليه"]])
df[["الاتصال أو التصادم"]] = ordinal_encoder_1.fit_transform(df[["الاتصال أو التصادم"]])

ordinal_encoder_2 = OrdinalEncoder(categories=[["الرابع الإبتدائي", "السادس الإبتدائي", "الأول إعدادى", "الثالث إعدادى"]])
df[["الصف الدراسي"]] = ordinal_encoder_2.fit_transform(df[["الصف الدراسي"]])

In [11]:
one_hot_cols = [
    "التصنيفات المرضية",
    "التغيرات في الجشطالت",
    "التسلسل",
    "ملاحظات دالة بشكل عام"
]

df = pd.get_dummies(df, columns=one_hot_cols)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 87 columns):
 #   Column                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                           --------------  -----
 0   النوع                                                                                                                                                            89 non-null     int64
 1   الصف الدراسي                                                                                                                                                     89 non-null     float64
 2   العمر                                                                                                                                                            89 non-null     int64
 3   موضع الرسم                                                                                                                                                       89 non-null     int64
 4   المسافة بين رسمين                                                                                                                                                89 non-null     int64
 5   الاتصال أو التصادم                                                                                                                                               89 non-null     float64
 6   استخدام الهامش                                                                                                                                                   89 non-null     int64
 7   تغيير موضع الورقة                                                                                                                                                89 non-null     int64
 8   التعليق العام                                                                                                                                                    89 non-null     object
 9   التصنيفات المرضية_التخلف العقلي                                                                                                                                  89 non-null     bool
 10  التصنيفات المرضية_العصاب                                                                                                                                         89 non-null     bool
 11  التصنيفات المرضية_سوي                                                                                                                                            89 non-null     bool
 12  التغيرات في الجشطالت_التغير في الإنحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة                                                                    89 non-null     bool
 13  التغيرات في الجشطالت_التغير في الانحناءات                                                                                                                        89 non-null     bool
 14  التغيرات في الجشطالت_التغير في الانحناءات, التغير في حجم الزوايا                                                                                                 89 non-null     bool
 15  التغيرات في الجشطالت_التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم                                                                               89 non-null     bool
 16  التغيرات في الجشطالت_التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة                                                  89 non-null     bool
 17  التغيرات في الجشطالت_التغير في الانحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة                                                                    89 non-null     bool
 18  التغيرات في الجشطالت_التغير في الانحناءات, تدوير محور الرسم                                                                                                      89 non-null     bool
 19  التغيرات في الجشطالت_التغير في الانحناءات, صعوبة رسم الأشكال المتداخلة                                                                                           89 non-null     bool
 20  التغيرات في الجشطالت_التغير في حجم الزوايا                                                                                                                       89 non-null     bool
 21  التغيرات في الجشطالت_التغير في حجم الزوايا, تبسيط الرسم                                                                                                          89 non-null     bool
 22  التغيرات في الجشطالت_التغير في حجم الزوايا, تدوير محور الرسم                                                                                                     89 non-null     bool
 23  التغيرات في الجشطالت_التغير في حجم الزوايا, تدوير محور الرسم, تجزئة الجشطالت                                                                                     89 non-null     bool
 24  التغيرات في الجشطالت_التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة                                                                        89 non-null     bool
 25  التغيرات في الجشطالت_صعوبات الإغلاق                                                                                                                              89 non-null     bool
 26  التغيرات في الجشطالت_صعوبات الإغلاق ,صعوبات تقاطع , التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, تبسيط الرسم, صعوبة رسم الأشكال المتداخلة      89 non-null     bool
 27  التغيرات في الجشطالت_صعوبات الإغلاق - التغير في الانحناءات, التغير في حجم الزوايا- صعوبة رسم الأشكال المتداخلة                                                   89 non-null     bool
 28  التغيرات في الجشطالت_صعوبات الإغلاق, التغير في الانحناءات                                                                                                        89 non-null     bool
 29  التغيرات في الجشطالت_صعوبات الإغلاق, التغير في الانحناءات, التغير في حجم الزوايا                                                                                 89 non-null     bool
 30  التغيرات في الجشطالت_صعوبات الإغلاق, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم                                                               89 non-null     bool
 31  التغيرات في الجشطالت_صعوبات الإغلاق, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة                                  89 non-null     bool
 32  التغيرات في الجشطالت_صعوبات الإغلاق, التغير في الانحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة                                                    89 non-null     bool
 33  التغيرات في الجشطالت_صعوبات الإغلاق, التغير في الانحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة, تدوير محور الرسم                                  89 non-null     bool
 34  التغيرات في الجشطالت_صعوبات الإغلاق, تبسيط الرسم, التغير في الانحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة                                       89 non-null     bool
 35  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات,  تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة                                        89 non-null     bool
 36  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا                                                                 89 non-null     bool
 37  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تبسيط الرسم                                                    89 non-null     bool
 38  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تبسيط الرسم, تجزئة الجشطالت, صعوبة رسم الأشكال المتداخلة       89 non-null     bool
 39  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تبسيط الرسم, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة     89 non-null     bool
 40  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تبسيط الرسم, صعوبة رسم الأشكال المتداخلة                       89 non-null     bool
 41  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تجزئة الجشطالت, صعوبة رسم الأشكال المتداخلة                    89 non-null     bool
 42  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, تبسيط الرسم, صعوبة رسم الأشكال المتداخلة     89 non-null     bool
 43  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, تبسيط, صعوبة رسم الأشكال المتداخلة           89 non-null     bool
 44  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, تجزئة الجشطالت, صعوبة رسم الأشكال المتداخلة  89 non-null     bool
 45  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة                  89 non-null     bool
 46  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, لا يوجد                                      89 non-null     bool
 47  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, صعوبة رسم الأشكال المتداخلة                                    89 non-null     bool
 48  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في الانحناءات, صعوبة رسم الأشكال المتداخلة                                                           89 non-null     bool
 49  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبات التقاطع, التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة                                        89 non-null     bool
 50  التغيرات في الجشطالت_صعوبات الإغلاق, صعوبة رسم الأشكال المتداخلة                                                                                                 89 non-null     bool
 51  التغيرات في الجشطالت_صعوبات التقاطع                                                                                                                              89 non-null     bool
 52  التغيرات في الجشطالت_صعوبات التقاطع, التغير في الانحناءات                                                                                                        89 non-null     bool
 53  التغيرات في الجشطالت_صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا                                                                                 89 non-null     bool
 54  التغيرات في الجشطالت_صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تجزئة الجشطالت                                                                 89 non-null     bool
 55  التغيرات في الجشطالت_صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم                                                               89 non-null     bool
 56  التغيرات في الجشطالت_صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, تبسيط الرسم, تجزئة الجشطالت, صعوبة رسم الأشكال المتداخلة     89 non-null     bool
 57  التغيرات في الجشطالت_صعوبات التقاطع, التغير في الانحناءات, التغير في حجم الزوايا, تدوير محور الرسم, صعوبة رسم الأشكال المتداخلة                                  89 non-null     bool
 58  التغيرات في الجشطالت_صعوبات التقاطع, تجزئة الجشطالت                                                                                                              89 non-null     bool
 59  التغيرات في الجشطالت_صعوبات تقاطع , التغير في الانحناءات, تبسيط الرسم                                                                                            89 non-null     bool
 60  التسلسل_تسلسل ثابت                                                                                                                                               89 non-null     bool
 61  التسلسل_تسلسل غير منظم                                                                                                                                           89 non-null     bool
 62  التسلسل_تسلسل مرتبك                                                                                                                                              89 non-null     bool
 63  التسلسل_تسلسل منظم                                                                                                                                               89 non-null     bool
 64  ملاحظات دالة بشكل عام_إعادة رسم الأجزاء (خطوط ثقيلة)                                                                                                             89 non-null     bool
 65  ملاحظات دالة بشكل عام_إعادة رسم الأجزاء (خطوط ثقيلة), اندفاع وسرعة في الرسم                                                                                      89 non-null     bool
 66  ملاحظات دالة بشكل عام_إعادة رسم الأجزاء (خطوط ثقيلة), رسم فواصل بين الأشكال                                                                                      89 non-null     bool
 67  ملاحظات دالة بشكل عام_إعادة رسم الأجزاء (خطوط ثقيلة), رسم كاريكاتيري                                                                                             89 non-null     bool
 68  ملاحظات دالة بشكل عام_استخدام أكثر من اتجاه                                                                                                                      89 non-null     bool
 69  ملاحظات دالة بشكل عام_استخدام أكثر من اتجاه, إعادة رسم الأجزاء (خطوط ثقيلة)                                                                                      89 non-null     bool
 70  ملاحظات دالة بشكل عام_استخدام أكثر من اتجاه, إعادة رسم الأجزاء (خطوط ثقيلة), اندفاع وسرعة في الرسم, رسم فواصل بين الأشكال, رسم كاريكاتيري                        89 non-null     bool
 71  ملاحظات دالة بشكل عام_استخدام أكثر من اتجاه, رسم فواصل بين الأشكال                                                                                               89 non-null     bool
 72  ملاحظات دالة بشكل عام_استخدام أكثر من اتجاه, رسم كاريكاتيري                                                                                                      89 non-null     bool
 73  ملاحظات دالة بشكل عام_الرسم من أسفل لأعلى, إعادة رسم الأجزاء (خطوط ثقيلة), اندفاع وسرعة في الرسم                                                                 89 non-null     bool
 74  ملاحظات دالة بشكل عام_الرسم من أسفل لأعلى, استخدام أكثر من اتجاه                                                                                                 89 non-null     bool
 75  ملاحظات دالة بشكل عام_الرسم من أسفل لأعلى, استخدام أكثر من اتجاه, إعادة رسم الأجزاء (خطوط ثقيلة)                                                                 89 non-null     bool
 76  ملاحظات دالة بشكل عام_المداومة                                                                                                                                   89 non-null     bool
 77  ملاحظات دالة بشكل عام_المداومة, إعادة رسم الأجزاء (خطوط ثقيلة)                                                                                                   89 non-null     bool
 78  ملاحظات دالة بشكل عام_المداومة, إعادة رسم الأجزاء (خطوط ثقيلة), رسم كاريكاتيري                                                                                   89 non-null     bool
 79  ملاحظات دالة بشكل عام_المداومة, اندفاع وسرعة في الرسم                                                                                                            89 non-null     bool
 80  ملاحظات دالة بشكل عام_المداومة, رسم فواصل بين الأشكال                                                                                                            89 non-null     bool
 81  ملاحظات دالة بشكل عام_اندفاع وسرعة في الرسم, المداومة                                                                                                            89 non-null     bool
 82  ملاحظات دالة بشكل عام_رسم فواصل بين الأشكال                                                                                                                      89 non-null     bool
 83  ملاحظات دالة بشكل عام_رسم فواصل بين الأشكال, إعادة رسم الأجزاء (خطوط ثقيلة)                                                                                      89 non-null     bool
 84  ملاحظات دالة بشكل عام_رسم كاريكاتيري                                                                                                                             89 non-null     bool
 85  ملاحظات دالة بشكل عام_لا يوجد                                                                                                                                    89 non-null     bool
 86  ملاحظات دالة بشكل عام_مداومة, رسم فواصل بين الأشكال                                                                                                              89 non-null     bool
dtypes: bool(78), float64(2), int64(6), object(1)
memory usage: 13.2+ KB

In [13]:
df.head(26)

,النوع,الصف الدراسي,العمر,موضع الرسم,المسافة بين رسمين,الاتصال أو التصادم,استخدام الهامش,تغيير موضع الورقة,التعليق العام,التصنيفات المرضية_التخلف العقلي,...,"ملاحظات دالة بشكل عام_المداومة, إعادة رسم الأجزاء (خطوط ثقيلة)","ملاحظات دالة بشكل عام_المداومة, إعادة رسم الأجزاء (خطوط ثقيلة), رسم كاريكاتيري","ملاحظات دالة بشكل عام_المداومة, اندفاع وسرعة في الرسم","ملاحظات دالة بشكل عام_المداومة, رسم فواصل بين الأشكال","ملاحظات دالة بشكل عام_اندفاع وسرعة في الرسم, المداومة",ملاحظات دالة بشكل عام_رسم فواصل بين الأشكال,"ملاحظات دالة بشكل عام_رسم فواصل بين الأشكال, إعادة رسم الأجزاء (خطوط ثقيلة)",ملاحظات دالة بشكل عام_رسم كاريكاتيري,ملاحظات دالة بشكل عام_لا يوجد,"ملاحظات دالة بشكل عام_مداومة, رسم فواصل بين الأشكال"
0,1,0.0,9,0,1,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,False,False,False,False,False,False,False,False,True,False
1,1,0.0,9,0,1,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,False,False,False,False,False,False,False,False,False,False
2,1,0.0,9,0,1,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بمستوى متوسط من ال...,False,...,False,False,False,False,True,False,False,False,False,False
3,1,0.0,10,0,0,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بقدرة متوسطة على ا...,False,...,False,False,False,False,False,False,False,False,False,False
4,1,0.0,11,0,0,2.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,False,False,False,False,False,False,False,False,True,False
5,1,0.0,10,0,1,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,False,False,False,False,False,False,False,False,False,False
6,1,0.0,11,0,1,2.0,0,0,يعانى المفحوص من ضعف التأزر البصري الحركي - وض...,True,...,False,False,False,False,False,False,False,False,False,False
7,1,0.0,10,0,1,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,False,False,False,False,False,False,False,False,False,False
8,1,0.0,10,0,1,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,False,False,False,False,False,False,False,False,False,False
9,1,0.0,9,0,1,2.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,True,False,False,False,False,False,False,False,False,False
10,1,0.0,11,0,1,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,False,False,False,False,False,False,False,False,True,False
11,1,0.0,9,0,1,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,False,False,False,False,False,False,False,False,False,False
12,1,0.0,10,0,1,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,False,False,False,False,False,False,False,False,False,False
13,0,0.0,10,0,0,0.0,0,0,المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأ...,False,...,False,False,False,False,False,False,False,False,False,False
14,0,0.0,11,0,1,0.0,0,0,المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأ...,False,...,False,False,False,False,False,False,False,False,False,False
15,0,0.0,9,0,1,0.0,0,0,المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأ...,False,...,False,False,False,False,False,False,False,False,False,False
16,0,0.0,10,0,0,2.0,0,0,المفحوصة بشكل عام تعاني من خلل إدراكي وضعف في ...,False,...,False,False,False,False,False,False,False,False,False,False
17,0,0.0,10,0,1,0.0,0,0,المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأ...,False,...,False,False,False,False,False,False,True,False,False,False
18,0,0.0,11,0,1,0.0,0,0,المفحوصة بشكل عام تعاني من ضعف في القدرة على ا...,False,...,False,False,False,False,False,False,False,True,False,False
19,0,0.0,10,0,1,0.0,0,0,المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأ...,False,...,False,False,False,False,False,False,False,False,False,True
20,0,0.0,10,0,1,0.0,0,0,المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأ...,False,...,False,False,False,False,False,False,False,False,False,False
21,0,0.0,9,0,1,0.0,0,0,المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأ...,False,...,False,False,False,False,False,False,False,False,False,False
22,0,0.0,10,0,0,2.0,0,0,المفحوصة بشكل عام تعاني من العصاب وتتمتع بمستو...,False,...,False,False,False,False,False,False,False,False,False,False
23,0,0.0,10,0,1,0.0,0,0,المفحوصة بشكل عام سوية وتتمتع بالقدرة على التأ...,False,...,False,False,False,False,False,True,False,False,False,False
24,1,1.0,11,0,0,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,False,False,False,False,False,False,False,False,False,False
25,1,1.0,12,0,1,0.0,0,0,المفحوص بشكل عام سوي ويتمتع بالقدرة على التأزر...,False,...,False,False,False,False,False,False,False,False,True,False

Extract impportant info from text and drop it after

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

df["التعليق العام"] = df["التعليق العام"].fillna("")

tfidf = TfidfVectorizer(max_features=100)

tfidf_matrix = tfidf.fit_transform(df["التعليق العام"])

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf.get_feature_names_out(),
    index=df.index
)

df = pd.concat([df, tfidf_df], axis=1)

df.drop("التعليق العام", axis=1, inplace=True)

In [15]:
df.head()

,النوع,الصف الدراسي,العمر,موضع الرسم,المسافة بين رسمين,الاتصال أو التصادم,استخدام الهامش,تغيير موضع الورقة,التصنيفات المرضية_التخلف العقلي,التصنيفات المرضية_العصاب,...,ولكنه,ولكنها,ومخاوف,ومشاعر,ونشاط,ونقص,ويتمتع,ويحتاج,يحتاج,يشعر
0,1,0.0,9,0,1,0.0,0,0,False,False,...,0.0,0.0,0.0,0.0,0.0,0.00000,0.171985,0.0,0.0,0.0
1,1,0.0,9,0,1,0.0,0,0,False,False,...,0.0,0.0,0.0,0.0,0.0,0.00000,0.163723,0.0,0.0,0.0
2,1,0.0,9,0,1,0.0,0,0,False,False,...,0.0,0.0,0.0,0.0,0.0,0.00000,0.113180,0.0,0.0,0.0
3,1,0.0,10,0,0,0.0,0,0,False,False,...,0.0,0.0,0.0,0.0,0.0,0.22917,0.123466,0.0,0.0,0.0
4,1,0.0,11,0,0,2.0,0,0,False,False,...,0.0,0.0,0.0,0.0,0.0,0.00000,0.192874,0.0,0.0,0.0

To convert PDF file to images to attach it with columns in excel file

In [18]:
!apt-get install poppler-utils
!pip install pdf2image

from pdf2image import convert_from_path

images = convert_from_path("/content/صور اوراق الطلاب.pdf")

for i, img in enumerate(images):
    img.save(f"image_{i}.jpg", "JPEG")

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 186 kB of archives.
After this operation, 697 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 poppler-utils amd64 22.02.0-2ubuntu0.12 [186 kB]
Fetched 186 kB in 1s (136 kB/s)
Selecting previously unselected package poppler-utils.
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../poppler-utils_22.02.0-2ubuntu0.12_amd64.deb ...
Unpacking poppler-utils (22.02.0-2ubuntu0.12) ...
Setting up poppler-utils (22.02.0-2ubuntu0.12) ...
Processing triggers for man-db (2.10.2-1) ...
Requirement already satisfied: pdf2image in /usr/local/lib/python3.12/dist-packages (1.17.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from pdf2image) (11.3.0)

Now , we need to add column in dataset to match with images